apiVersion: v1
kind: Pod
metadata:
  labels:
    run: secret-xfusion
  name: secret-xfusion
spec:
  volumes:
    - name: data
      secret:
        secretName: official
  containers:
  - image: debian:latest
    name: secret-container-xfusion
    command: ['/bin/sh', '-c', 'sleep 3600']
    volumeMounts:
      - name: data
        mountPath: /opt/games
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}