apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana-deployment-xfusion
  name: grafana-deployment-xfusion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-deployment-xfusion
  strategy: {}
  template:
    metadata:
      labels:
        app: grafana-deployment-xfusion
    spec:
      containers:
      - image: grafana/grafana
        name: grafana
        ports:
        - containerPort: 3000
        resources: {}
status: {}